# Basic
title: Halfrost's Field | 冰霜之地
subtitle: 一缕殇流，化隐半边冰霜
description: 嗨，我是于德志 (@halfrost)，一名来自中国的 iOS 开发者，已退役 acmer 。现居上海。吾笃信：德不孤，必有志，技不疏，必有朋。
creator: <a href="http://halfrost.com">@halfrost</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: black

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: 关于, url: 'http://about.halfrost.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page/:num/"

# Comment
comment:
    disqus: halfrostsfield
    # duoshuo:vno-jekyll

# Social
social:
    weibo: halfrost
    github: halfrost
    jianshu: halfrost
    #gplus: 113872186786618065577
    mail: ydz627@gamil.com


# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
